/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vistas;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.Alquiler;
import logica.Inquilino;
import logica.Vivienda;

/**
 *
 * @author vitts
 */
public class DlgGestionAlquileres extends javax.swing.JDialog {

    private ArrayList<Alquiler> listaAlquileres;
    private ArrayList<Inquilino> listaInquilinos;
    private ArrayList<Vivienda> listaViviendas;
    private DefaultTableModel modelo;
    
    
   public DlgGestionAlquileres(java.awt.Frame parent, boolean modal,
        ArrayList<Alquiler> listaAlquileres,
        ArrayList<Inquilino> listaInquilinos,
        ArrayList<Vivienda> listaViviendas) {
    super(parent, modal);
    initComponents();
    this.listaAlquileres =listaAlquileres;
    this.listaInquilinos = listaInquilinos;
    this.listaViviendas = listaViviendas;
    muestraTabla();

    }
   public ArrayList<Alquiler> getListaAlquileres() {
    return listaAlquileres;
}
   
   private void muestraTabla() {
    String[] titulos = {"N° Alquiler", "Fecha Contrato", "Meses", "Inquilino", 
                         "Vivienda", "Precio", "Estado"};
    modelo = new DefaultTableModel(null, titulos) {
        @Override
        public boolean isCellEditable(int row, int col) {
            return false;
        }
    };
    tblAlquileres.setModel(modelo);
    modelo.setRowCount(0);

    for (Alquiler a : listaAlquileres) {
        String nombreInquilino = buscarNombreInquilino(a.getCedInquilino());
        String direccionVivienda = buscarDireccionVivienda(a.getIdVivienda());

        modelo.addRow(new Object[]{
            a.getNumAlquiler(), a.getFechContrato(), a.getCantMeses(),
            nombreInquilino, direccionVivienda, a.getPrecioAlquiler(), a.getEstado()
        });
    }
}

private String buscarNombreInquilino(long cedula) {
    for (Inquilino i : listaInquilinos) {
        if (i.getCedInqui() == cedula) {
            return i.getNomInqui();
        }
    }
    return "Desconocido";
}

private String buscarDireccionVivienda(int idVivienda) {
    for (Vivienda v : listaViviendas) {
        if (v.getIdVivienda() == idVivienda) {
            return v.getDireccion(); // ajusta al nombre real del getter en Vivienda
        }
    }
    return "Desconocida";
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCantClientes = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblBuscar = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAlquileres = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtCantAlquileres = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblCantClientes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblBuscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBuscar.setText("Buscar: ");

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarKeyReleased(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        tblAlquileres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "", "", "", "", "", ""
            }
        ));
        jScrollPane2.setViewportView(tblAlquileres);

        jLabel1.setText("Cant.Alquileres");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 761, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCantClientes)
                .addGap(786, 786, 786))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1)
                        .addGap(37, 37, 37)
                        .addComponent(txtCantAlquileres, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(lblCantClientes))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantAlquileres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
     int fila = tblAlquileres.getSelectedRow();
    if (fila == -1) {
        JOptionPane.showMessageDialog(this, "Seleccione un alquiler de la tabla para eliminar");
        return;
    }

    int numAlquiler = (int) modelo.getValueAt(fila, 0);
    int confirmacion = JOptionPane.showConfirmDialog(this,
            "¿Está seguro de eliminar este alquiler?", "Confirmar",
            JOptionPane.YES_NO_OPTION);

    if (confirmacion == JOptionPane.YES_OPTION) {
        Alquiler aEliminar = buscar(numAlquiler);
        if (aEliminar != null) {
            listaAlquileres.remove(aEliminar);
            JOptionPane.showMessageDialog(this, "Alquiler eliminado correctamente");
            muestraTabla();
        }
    }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
     int fila = tblAlquileres.getSelectedRow();
    if (fila == -1) {
        JOptionPane.showMessageDialog(this, "Seleccione un alquiler de la tabla para editar");
        return;
    }
    
    
    DlgNewAlquileres dlg = new DlgNewAlquileres((java.awt.Frame) this.getOwner(), true, 2,
            listaAlquileres, listaInquilinos, listaViviendas);
    dlg.setLocationRelativeTo(null);
    dlg.setVisible(true);
    muestraTabla();
    
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

    DlgNewAlquileres dlg = new DlgNewAlquileres((java.awt.Frame) this.getOwner(), true, 1,
            listaAlquileres, listaInquilinos, listaViviendas);
    dlg.setLocationRelativeTo(null);
    dlg.setVisible(true);
    muestraTabla();
    
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyReleased
        String filtro = txtBuscar.getText().trim().toLowerCase();
    modelo.setRowCount(0);
    for (Alquiler a : listaAlquileres) {
        String nombreInquilino = buscarNombreInquilino(a.getCedInquilino());
        if (String.valueOf(a.getNumAlquiler()).contains(filtro)
                || nombreInquilino.toLowerCase().contains(filtro)) {
            String direccionVivienda = buscarDireccionVivienda(a.getIdVivienda());
            modelo.addRow(new Object[]{
                a.getNumAlquiler(), a.getFechContrato(), a.getCantMeses(),
                nombreInquilino, direccionVivienda, a.getPrecioAlquiler(), a.getEstado()
            });
        }
    }
}

private Alquiler buscar(int numAlquiler) {
    for (Alquiler a : listaAlquileres) {
        if (a.getNumAlquiler() == numAlquiler) {
            return a;
        }
    }
    return null;
    }//GEN-LAST:event_txtBuscarKeyReleased

    /**
     * @param args the command line arguments
     */
   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblCantClientes;
    private javax.swing.JTable tblAlquileres;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCantAlquileres;
    // End of variables declaration//GEN-END:variables
}
