/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vistas;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.Alquiler;
import logica.Inquilino;
import logica.Vivienda;

/**
 *
 * @author vitts
 */
public class DlgNewAlquileres extends javax.swing.JDialog {

    private int modo;
private ArrayList<Alquiler> listaAlquileres;
private ArrayList<Inquilino> listaInquilinos;
private ArrayList<Vivienda> listaViviendas;
    
    
  
   public DlgNewAlquileres(java.awt.Frame parent, boolean modal, int modo,
        ArrayList<Alquiler> listaAlquileres,
        ArrayList<Inquilino> listaInquilinos,
        ArrayList<Vivienda> listaViviendas) {
    super(parent, modal);
    initComponents();
    this.modo = modo;
    this.listaAlquileres = listaAlquileres;
    this.listaInquilinos = listaInquilinos;
    this.listaViviendas = listaViviendas;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCantMeses = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnGuardar = new javax.swing.JButton();
        lblNumAdultos = new javax.swing.JLabel();
        txtCantMeses = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txtNumAdultos = new javax.swing.JTextField();
        lblNumNiños = new javax.swing.JLabel();
        txtNumNiños = new javax.swing.JTextField();
        lblDeposito = new javax.swing.JLabel();
        txtDeposito = new javax.swing.JTextField();
        lblPrecioAlquiler = new javax.swing.JLabel();
        txtPrecioAlquiler = new javax.swing.JTextField();
        txtPorcIncremAnual = new javax.swing.JLabel();
        txtPorcentajeIncrementadoAnual = new javax.swing.JTextField();
        lblCedInquilino = new javax.swing.JLabel();
        txtCedInquilino = new javax.swing.JTextField();
        lblIdVivienda = new javax.swing.JLabel();
        txtIDVivienda = new javax.swing.JTextField();
        lblEstado = new javax.swing.JLabel();
        lblNumAlquiler = new javax.swing.JLabel();
        cbmEstado = new javax.swing.JComboBox<>();
        txtNumeroAlquiler = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblFechContrato = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAlquileres = new javax.swing.JTable();
        txtFechaContrato = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblCantMeses.setText("Cantidad de Meses");

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        lblNumAdultos.setText("N Adultos");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        lblNumNiños.setText("N Niños");

        lblDeposito.setText("Deposito");

        lblPrecioAlquiler.setText("Precio Alquiler");

        txtPorcIncremAnual.setText("Porcentaje Incrementado Anual");

        lblCedInquilino.setText("Cedula Inquilino");

        lblIdVivienda.setText("ID Vivienda");

        lblEstado.setText("Estado");

        lblNumAlquiler.setText("N Alquiler");

        cbmEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vigente", "Vencido", "Cancelado" }));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "GESTION DE ALQUILERES", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 14))); // NOI18N

        lblFechContrato.setText("Fecha Contrato");

        tblAlquileres.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "N Alquiler", "Fecha Contrato", "Cant.Meses", "N Adultos", "N Niños", "Deposito", "Precio Alquiler", "Incremento", "Inquilino", "Vivienda", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tblAlquileres);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblPrecioAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPrecioAlquiler))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDeposito))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblNumNiños, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblNumAdultos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNumAdultos)
                                    .addComponent(txtNumNiños, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(103, 103, 103)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPorcIncremAnual, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPorcentajeIncrementadoAnual, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCantMeses, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCantMeses, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblFechContrato)
                                        .addGap(20, 20, 20)
                                        .addComponent(txtFechaContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblNumAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtNumeroAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(40, 40, 40)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblCedInquilino)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtCedInquilino, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblIdVivienda, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(cbmEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(txtIDVivienda, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGap(114, 114, 114)
                                        .addComponent(btnGuardar)
                                        .addGap(52, 52, 52)
                                        .addComponent(btnBuscar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnEditar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(104, 104, 104)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(36, 36, 36)
                        .addComponent(btnEliminar)
                        .addGap(9, 9, 9)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCedInquilino)
                            .addComponent(txtCedInquilino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNumAlquiler)
                            .addComponent(txtNumeroAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFechContrato)
                            .addComponent(txtFechaContrato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIdVivienda)
                            .addComponent(txtIDVivienda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEstado)
                            .addComponent(cbmEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCantMeses)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCantMeses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNumAdultos)
                            .addComponent(txtNumAdultos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNumNiños)
                            .addComponent(txtNumNiños, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDeposito)
                            .addComponent(txtDeposito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPrecioAlquiler)
                            .addComponent(txtPrecioAlquiler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPorcIncremAnual)
                            .addComponent(txtPorcentajeIncrementadoAnual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
  String numAlquiler = txtNumeroAlquiler.getText().trim();

    if (numAlquiler.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingrese un número de alquiler");
        return;
    }

    boolean encontrado = false;
    for (Alquiler a : listaAlquileres) {
        if (String.valueOf(a.getNumAlquiler()).equals(numAlquiler)) {
            a.setCantMeses(Integer.parseInt(txtCantMeses.getText().trim()));
            a.setNumAdultos(Integer.parseInt(txtNumAdultos.getText().trim()));
            a.setNumNinos(Integer.parseInt(txtNumNiños.getText().trim()));
            a.setDepositoGarantia(Double.parseDouble(txtDeposito.getText().trim()));
            a.setPrecioAlquiler(Double.parseDouble(txtPrecioAlquiler.getText().trim()));
            a.setPorcIncremAnual(Double.parseDouble(txtPorcentajeIncrementadoAnual.getText().trim()));
            a.setEstado((String) cbmEstado.getSelectedItem());
            encontrado = true;
            break;
        }
    }//GEN-LAST:event_btnEditarActionPerformed
}
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

  String numAlquiler = txtNumeroAlquiler.getText().trim();
    String fechContrato = txtFechaContrato.getText().trim();
    String cantMeses = txtCantMeses.getText().trim();
    String numAdultos = txtNumAdultos.getText().trim();
    String numNiños = txtNumNiños.getText().trim();
    String depositoGarantia = txtDeposito.getText().trim();
    String precioAlquiler = txtPrecioAlquiler.getText().trim();
    String porcIncremAnual = txtPorcentajeIncrementadoAnual.getText().trim();
    String cedInquilino = txtCedInquilino.getText().trim();
    String idVivienda = txtIDVivienda.getText().trim();
    String estado = (String) cbmEstado.getSelectedItem();

    if (numAlquiler.isEmpty() || fechContrato.isEmpty() || cantMeses.isEmpty()
            || depositoGarantia.isEmpty() || cedInquilino.isEmpty() || idVivienda.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor complete todos los campos obligatorios");
        return;
    }

    try {
        int nAlquiler = Integer.parseInt(numAlquiler);
        int cMeses = Integer.parseInt(cantMeses);
        int nAdultos = Integer.parseInt(numAdultos);
        int nNiños = Integer.parseInt(numNiños);
        double deposito = Double.parseDouble(depositoGarantia);
        double precio = Double.parseDouble(precioAlquiler);
        double porcIncrem = Double.parseDouble(porcIncremAnual);
        long cedInq = Long.parseLong(cedInquilino);
        int idViv = Integer.parseInt(idVivienda);

        java.time.format.DateTimeFormatter formatter =
                java.time.format.DateTimeFormatter.ofPattern("d/M/yyyy");
        java.time.LocalDate fecha = java.time.LocalDate.parse(fechContrato, formatter);

        if (modo == 1) {
            // Agregar nuevo alquiler
            Alquiler nuevo = new Alquiler(
                nAlquiler, fecha, cMeses, nAdultos, nNiños,
                deposito, precio, porcIncrem, cedInq, idViv, estado
            );
            listaAlquileres.add(nuevo);
        } else {
            // Editar alquiler existente
            Alquiler existente = buscar(nAlquiler);
            if (existente != null) {
                existente.setFechContrato(fecha);
                existente.setCantMeses(cMeses);
                existente.setNumAdultos(nAdultos);
                existente.setNumNinos(nNiños);
                existente.setDepositoGarantia(deposito);
                existente.setPrecioAlquiler(precio);
                existente.setPorcIncremAnual(porcIncrem);
                existente.setCedInquilino(cedInq);
                existente.setIdVivienda(idViv);
                existente.setEstado(estado);
            } else {
                JOptionPane.showMessageDialog(this, "No se encontró un alquiler con ese número");
                return;
            }
        }

        JOptionPane.showMessageDialog(this, "Alquiler guardado correctamente");
        
        limpiarCampos();
        this.dispose();

    } catch (java.time.format.DateTimeParseException e) {
        JOptionPane.showMessageDialog(this, "La fecha debe tener el formato día/mes/año (ej: 25/12/2026)");
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Revisa los campos numéricos, uno de ellos contiene texto inválido");
    }
}
 private Alquiler buscar(int numAlquiler) {
    for (Alquiler a : listaAlquileres) {
        if (a.getNumAlquiler() == numAlquiler) {
            return a;
        }
    }
    return null;
}

private void limpiarCampos() {
    txtNumeroAlquiler.setText("");
    txtFechaContrato.setText("");
    txtCantMeses.setText("");
    txtNumAdultos.setText("");
    txtNumNiños.setText("");
    txtDeposito.setText("");
    txtPrecioAlquiler.setText("");
    txtPorcentajeIncrementadoAnual.setText("");
    txtCedInquilino.setText("");
    txtIDVivienda.setText("");



    

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String numAlquiler = txtNumeroAlquiler.getText().trim();

    if (numAlquiler.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Ingrese un número de alquiler para buscar");
        return;
    }

    boolean encontrado = false;
    for (Alquiler a : listaAlquileres) {
        if (String.valueOf(a.getNumAlquiler()).equals(numAlquiler)) {
            txtFechaContrato.setText(a.getFechContrato().toString());
            txtCantMeses.setText(String.valueOf(a.getCantMeses()));
            txtNumAdultos.setText(String.valueOf(a.getNumAdultos()));
            txtNumNiños.setText(String.valueOf(a.getNumNinos()));
            txtDeposito.setText(String.valueOf(a.getDepositoGarantia()));
            txtPrecioAlquiler.setText(String.valueOf(a.getPrecioAlquiler()));
            txtPorcentajeIncrementadoAnual.setText(String.valueOf(a.getPorcIncremAnual()));
            txtCedInquilino.setText(String.valueOf(a.getCedInquilino()));
            txtIDVivienda.setText(String.valueOf(a.getIdVivienda()));
            cbmEstado.setSelectedItem(a.getEstado());
            encontrado = true;
            break;
        }
    }

    if (!encontrado) {
        JOptionPane.showMessageDialog(this, "No se encontró un alquiler con ese número");
    }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String numAlquiler = lblNumAlquiler.getText().trim();

        if (numAlquiler.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese un número de alquiler para eliminar");
            return;
        }

        Alquiler aEliminar = null;
        for (Alquiler a : listaAlquileres) {
            if (String.valueOf(a.getNumAlquiler()).equals(numAlquiler)) {
                aEliminar = a;
                break;
            }
        }

        if (aEliminar == null) {
            JOptionPane.showMessageDialog(this, "No se encontró un alquiler con ese número");
            return;
        }

        int confirmacion = JOptionPane.showConfirmDialog(this, "¿Está seguro de eliminar este alquiler?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);

        if (confirmacion == JOptionPane.YES_OPTION) {
            listaAlquileres.remove(aEliminar);
            JOptionPane.showMessageDialog(this, "Alquiler eliminado correctamente");
            
            limpiarCampos();
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
   
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cbmEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCantMeses;
    private javax.swing.JLabel lblCedInquilino;
    private javax.swing.JLabel lblDeposito;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFechContrato;
    private javax.swing.JLabel lblIdVivienda;
    private javax.swing.JLabel lblNumAdultos;
    private javax.swing.JLabel lblNumAlquiler;
    private javax.swing.JLabel lblNumNiños;
    private javax.swing.JLabel lblPrecioAlquiler;
    private javax.swing.JTable tblAlquileres;
    private javax.swing.JTextField txtCantMeses;
    private javax.swing.JTextField txtCedInquilino;
    private javax.swing.JTextField txtDeposito;
    private javax.swing.JTextField txtFechaContrato;
    private javax.swing.JTextField txtIDVivienda;
    private javax.swing.JTextField txtNumAdultos;
    private javax.swing.JTextField txtNumNiños;
    private javax.swing.JTextField txtNumeroAlquiler;
    private javax.swing.JLabel txtPorcIncremAnual;
    private javax.swing.JTextField txtPorcentajeIncrementadoAnual;
    private javax.swing.JTextField txtPrecioAlquiler;
    // End of variables declaration//GEN-END:variables
}
